/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uia.proyectofinal.View;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static sun.security.jgss.GSSUtil.login;
import uia.proyectofinal.Bussines.IS12Bussines;
import uia.proyectofinal.Conecciones.MySQLDB;
import uia.proyectofinal.Data.IS12DAO;
import uia.proyectofinal.Domain.Issue;
import uia.proyectofinal.Domain.Proyecto;
import uia.proyectofinal.Domain.Tareas;
import uia.proyectofinal.Domain.Users;

/**
 *
 * @author Bryan
 */
public class InternalTarea extends javax.swing.JInternalFrame {

    
    
    public InternalTarea() throws SQLException {
       
        initComponents();
        Login log = new Login();
        lblNombre.setText(log.getUser());
       lblPuesto.setText(log.getPuesto());
    MySQLDB mysql = new MySQLDB();
    String sql = "select *from proyecto.proyectos";
    ResultSet res = mysql.executeQuery(sql);
    
    while(res.next()){
        Proyecto proyecto = new Proyecto();
        ArrayList<Proyecto> proyectos = new ArrayList<Proyecto>();
        proyecto.setCodigo(res.getString("cod_proyecto"));
        jComboBox1.addItem(res.getString("cod_proyecto"));
    
    }
  
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTarea2 = new javax.swing.JTextField();
        txtTarea3 = new javax.swing.JTextField();
        btrAsignarTareas = new javax.swing.JButton();
        btrModificar = new javax.swing.JButton();
        txtTarea = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        btnGenerar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento de Tareas");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 555));

        jLabel1.setText("Tareas a Asignar :");

        btrAsignarTareas.setText("Asignar Tareas");
        btrAsignarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrAsignarTareasActionPerformed(evt);
            }
        });

        btrModificar.setText("Modificar Tareas Asignadas");
        btrModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrModificarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Puesto :");

        lblPuesto.setText("jLabel5");

        lblNombre.setText("jLabel6");

        jLabel5.setText("Nombre del Empleado :");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo del proyecto destinado :");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Selecionar Issue :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No tiene Issue" }));

        btnGenerar.setText("Generar Opciones ");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btrAsignarTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(btrModificar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(txtTarea3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(85, 85, 85)
                                        .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(66, 66, 66)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTarea2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGenerar)))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(lblNombre)
                    .addComponent(lblPuesto))
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(txtTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTarea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTarea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btrAsignarTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btrModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btrAsignarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrAsignarTareasActionPerformed
        try {
             Login log = new Login();
        
        Tareas tarea = new Tareas();
            IS12Bussines is12B = new IS12Bussines();
        Users user = new Users();
       Issue issue = new Issue();
        ArrayList<String> asig = new ArrayList<String>();
        asig.add(txtTarea.getText());
        asig.add(txtTarea2.getText());
        asig.add(txtTarea3.getText());
        tarea.setUser(txtNombre.getText());
        tarea.setAsignacion(asig);
        tarea.setCod_proyect((String) jComboBox1.getSelectedItem());
        issue.setNombre((String) jComboBox2.getSelectedItem());
        tarea.setIssues(issue);
        is12B.addTarea(tarea);
        
  
  
        } catch (SQLException ex) {
            Logger.getLogger(InternalTarea.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        txtTarea.setText(" ");
        txtTarea2.setText(" ");
        txtTarea3.setText(" ");
        txtNombre.setText(" ");
       
       
    }//GEN-LAST:event_btrAsignarTareasActionPerformed

    private void btrModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrModificarActionPerformed
 try {
          IS12Bussines is12B = new IS12Bussines();
        ArrayList<String> asig =new ArrayList<String>();
        Tareas tarea = new Tareas();
        IS12DAO is12 = new IS12DAO();
        Users user = new Users();
        Issue issue = new Issue();
       asig.add(txtTarea.getText());
        asig.add(txtTarea2.getText());
        asig.add(txtTarea3.getText());
      tarea.setUser(txtNombre.getText());
        tarea.setAsignacion(asig);
 tarea.setCod_proyect((String) jComboBox1.getSelectedItem());
  issue.setNombre((String) jComboBox2.getSelectedItem());
        tarea.setIssues(issue);
        is12B.updateTarea(tarea);
            
        
        } catch (SQLException ex) {
            Logger.getLogger(InternalTarea.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
          
        txtTarea.setText(" ");
        txtTarea2.setText(" ");
        txtTarea3.setText(" ");
         
    }//GEN-LAST:event_btrModificarActionPerformed

    @SuppressWarnings("empty-statement")
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        MySQLDB mysql = new MySQLDB();

    String sql = "select *from proyecto.proyectos";
    ResultSet res= mysql.executeQuery(sql);;
     jComboBox1.removeAllItems();
   
      while(res.next()){
       
      jComboBox1.addItem(res.getString("cod_proyecto"));
   
    }       
         
        } catch (SQLException ex) {
            Logger.getLogger(InternalTarea.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
     try { 
        
     MySQLDB mysql = new MySQLDB();
     String sql = "select *from proyecto.issues";

    ResultSet res = mysql.executeQuery(sql);
     while(res.next()){
        
        jComboBox2.addItem(res.getString("Nombre_Issue"));
    
     }
            
        } catch (SQLException ex) {
            Logger.getLogger(InternalTarea.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btrAsignarTareas;
    private javax.swing.JButton btrModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTarea;
    private javax.swing.JTextField txtTarea2;
    private javax.swing.JTextField txtTarea3;
    // End of variables declaration//GEN-END:variables

    
    public ArrayList<String> getTareas(){
        ArrayList<String> tarea = new ArrayList<String>();
   
    
    return null;
    }
}
